/**
 * build.mjs — Teacher AI Club
 * Fetches your live tool directory from Airtable at BUILD TIME and injects it
 * into index.html, producing a fast static site in /dist for Cloudflare Pages.
 *
 * Your Airtable token is read from an environment variable and NEVER ends up
 * in the published HTML. The FREE public build ships only the NUMBER of use
 * cases per tool (useCaseCount) — the premium Use Case text is intentionally
 * left out, so it can't be scraped from the page.
 *
 * Run locally:   node build.mjs        (reads a local .env if present)
 * On Cloudflare: build command = `npm run build`, output dir = `dist`
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";

/* ---- tiny .env loader (so local runs work on any Node 18+ without extra deps) ---- */
if (existsSync(".env")) {
  const env = await readFile(".env", "utf8");
  for (const line of env.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

/* ---- config (all overridable via environment variables) ---- */
const TOKEN   = process.env.AIRTABLE_TOKEN;
const BASE_ID = process.env.AIRTABLE_BASE_ID;
const TABLE   = process.env.AIRTABLE_TABLE || "Tools";        // your table name
const VIEW    = process.env.AIRTABLE_VIEW  || "";             // optional: a specific view

/* Airtable column name -> stays in one place so it's easy to adjust */
const FIELD = {
  toolName:    "Tool Name",
  description: "Description",
  toolType:    "Tool Type",
  gradeLevel:  "Grade Level",
  tags:        "Tags",
  url:         "URL",
  useCases:    ["Use Case 1", "Use Case 2", "Use Case 3"],
};

if (!TOKEN || !BASE_ID) {
  console.error("\n✗ Missing AIRTABLE_TOKEN or AIRTABLE_BASE_ID.");
  console.error("  Set them as environment variables (or in a local .env file).");
  console.error("  See README.md → 'Getting your Airtable token & base ID'.\n");
  process.exit(1);
}

/* turn multi-select arrays OR comma/newline strings into a clean array */
function toArray(v) {
  if (Array.isArray(v)) return v.map(s => String(s).trim()).filter(Boolean);
  if (typeof v === "string") return v.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
  return [];
}

async function fetchAllRecords() {
  const base = `https://api.airtable.com/v0/${BASE_ID}/${encodeURIComponent(TABLE)}`;
  const records = [];
  let offset;
  do {
    const params = new URLSearchParams({ pageSize: "100" });
    if (VIEW) params.set("view", VIEW);
    if (offset) params.set("offset", offset);
    const res = await fetch(`${base}?${params}`, {
      headers: { Authorization: `Bearer ${TOKEN}` },
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Airtable ${res.status} ${res.statusText}\n${body}`);
    }
    const data = await res.json();
    records.push(...data.records);
    offset = data.offset;
  } while (offset);
  return records;
}

function mapRecord(rec) {
  const f = rec.fields || {};
  const name = (f[FIELD.toolName] || "").toString().trim();
  if (!name) return null; // skip blank rows
  const useCaseCount = FIELD.useCases.reduce(
    (n, key) => n + (f[key] && String(f[key]).trim() ? 1 : 0), 0
  );
  return {
    toolName:    name,
    description: (f[FIELD.description] || "").toString().trim(),
    toolType:    (f[FIELD.toolType] || "Other").toString().trim(),
    gradeLevel:  toArray(f[FIELD.gradeLevel]),
    tags:        toArray(f[FIELD.tags]),
    url:         (f[FIELD.url] || "#").toString().trim(),
    useCaseCount, // count only — premium text never leaves Airtable
  };
}

async function main() {
  console.log(`→ Fetching from Airtable base ${BASE_ID}, table "${TABLE}"${VIEW ? `, view "${VIEW}"` : ""}…`);
  const raw = await fetchAllRecords();
  const tools = raw.map(mapRecord).filter(Boolean)
                   .sort((a, b) => a.toolName.localeCompare(b.toolName));
  console.log(`→ Mapped ${tools.length} tools.`);

  const template = await readFile("index.html", "utf8");
  const marker = /\/\*__TOOLS_START__[\s\S]*?__TOOLS_END__\*\//;
  if (!marker.test(template)) {
    throw new Error("Could not find the /*__TOOLS_START__*/ … /*__TOOLS_END__*/ markers in index.html");
  }
  const injection =
    `/*__TOOLS_START__  (auto-generated by build.mjs — do not edit by hand) */\n` +
    `const TOOLS = ${JSON.stringify(tools)};\n` +
    `/*__TOOLS_END__*/`;
  const html = template.replace(marker, () => injection);

  await mkdir("dist", { recursive: true });
  await writeFile("dist/index.html", html);
  console.log(`✓ Wrote dist/index.html (${tools.length} tools, ${(html.length / 1024).toFixed(0)} KB).`);
}

main().catch(err => { console.error("\n✗ Build failed:\n" + err.message + "\n"); process.exit(1); });
